name: 🚀 Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy-cz-prod:
        if: github.ref == 'refs/heads/master'
        name: CZ PRODUCTION
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: 📂 Deploy to Server
              run: bash .github/workflows/deploy.sh
              env:
                  FTP_HOST: ${{ vars.FTP_HOST }}
                  FTP_USER: ${{ vars.FTP_USER_CZ_PROD }}
                  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD_CZ_PROD }}
                  GIT_PREV_SHA: ${{ github.event.before }}
                  GIT_CURR_SHA: ${{ github.sha }}
